# 基于rating2inter.ipynb生成的5-core交互图，Train/Validation/Test data splitting
- Based on generated interactions, perform data splitting

In [1]:
import os, csv
import pandas as pd

In [4]:
os.chdir('/home/minhle/CaMRec/data')
os.getcwd()

'/home/minhle/CaMRec/data'

## 直接加载现成的, Load interactions

In [5]:
rslt_file = 'baby-indexed.inter'
df = pd.read_csv(rslt_file, sep='\t')
print(f'shape: {df.shape}')
df[:4]

shape: (160792, 5)

   userID  itemID  rating   timestamp  x_label
0       0       0     5.0  1373932800        0
1       1       0     5.0  1372464000        0
2       3       0     5.0  1376697600        0
3       6       0     5.0  1374019200        0

In [6]:
import random
import numpy as np

In [7]:

df = df.sample(frac=1).reset_index(drop=True)

df.sort_values(by=['userID'], inplace=True)
df[:20]

        userID  itemID  rating   timestamp  x_label
37004        0    3870     4.0  1357689600        0
101836       0    1879     5.0  1373932800        0
117802       0    1922     5.0  1363996800        0
155842       0    1587     5.0  1373932800        0
20530        0       0     5.0  1373932800        0
137704       1    1434     5.0  1372377600        0
38052        1       0     5.0  1372464000        0
40236        1    5176     5.0  1372464000        0
154030       1    1177     5.0  1372464000        0
101481       1    5403     5.0  1367452800        0
15671        1    2828     5.0  1372464000        0
4613         2    2846     2.0  1395187200        1
38495        2       0     5.0  1395187200        1
7832         2    6578     3.0  1387497600        0
142678       2    4011     5.0  1387497600        0
121376       2    6735     5.0  1395187200        1
61509        3    1886     5.0  1376697600        0
109518       3     638     4.0  1376697600        0
30241        3    2755     2.0  1376697600        0
93692        3       0     5.0  1376697600        0

In [8]:
uid_field, iid_field = 'userID', 'itemID'

uid_freq = df.groupby(uid_field)[iid_field]
u_i_dict = {}
for u, u_ls in uid_freq:
    u_i_dict[u] = list(u_ls)
u_i_dict

{0: [3870, 1879, 1922, 1587, 0],
 1: [1434, 0, 5176, 1177, 5403, 2828],
 2: [2846, 0, 6578, 4011, 6735],
 3: [1886, 638, 2755, 0, 6320, 2194],
 4: [5156, 0, 3408, 5070, 5523],
 5: [4914, 1372, 0, 6291, 5342],
 6: [1308, 5374, 1232, 5431, 5058, 6244, 0, 771, 4144, 3063, 6166],
 7: [0, 4832, 4657, 3183, 2252],
 8: [5606, 0, 6716, 2146, 1143, 1454, 5166, 5494, 3664, 3485, 1307, 3408],
 9: [832,
  6730,
  1,
  4626,
  5519,
  4367,
  4788,
  4793,
  6498,
  0,
  4666,
  6266,
  1210,
  6473,
  5987],
 10: [2089, 5417, 4310, 4445, 2045, 0, 2368],
 11: [3661, 2300, 6165, 5352, 5617, 5125, 0],
 12: [2312, 2759, 6145, 0, 4339, 1755, 4520, 6579, 2975],
 13: [3946, 0, 5416, 3131, 1689],
 14: [473, 1158, 6072, 14, 4297, 1169, 4240, 5428, 0],
 15: [4790,
  6732,
  6814,
  5918,
  6859,
  6210,
  6575,
  4284,
  4695,
  3726,
  6937,
  5955,
  5069,
  6747,
  6728,
  6902,
  6807,
  0],
 16: [2459, 345, 1500, 3305, 6706, 0, 1179, 5479],
 17: [1880, 1, 3341, 176, 830],
 18: [4045,
  6724,
  3179,
  1683,
  2651,
  1221,
  4888,
  3262,
  1,
  4931,
  4277,
  3314,
  4935,
  3755,
  2765,
  5365,
  2969],
 19: [849,
  6416,
  2534,
  1372,
  5597,
  1,
  119,
  5864,
  954,
  256,
  121,
  1024,
  1467,
  5397,
  1070,
  4350,
  3866,
  1201],
 20: [5455, 3009, 727, 4197, 3183, 2509, 1055, 5412, 3553, 1, 829, 3400, 3928],
 21: [2637, 5023, 1, 4843, 244, 5441, 663, 6451, 5689, 2807, 594],
 22: [1, 178, 3514, 3830, 6886],
 23: [3437,
  6483,
  2921,
  3364,
  5684,
  3059,
  3182,
  200,
  6252,
  1632,
  2449,
  5546,
  1482,
  1572,
  5397,
  3371,
  3601,
  1070,
  4190,
  6174,
  5476,
  2837,
  5448,
  6417,
  2701,
  5948,
  2952,
  4251,
  4147,
  363,
  3776,
  1],
 24: [4893, 4192, 3765, 2668, 1886, 1, 579, 623, 2459, 1576],
 25: [1649, 4664, 1308, 4695, 4893, 419, 1174, 1, 4037, 6651, 3956, 3963],
 26: [1886, 1, 5614, 771, 6867, 997],
 27: [2755, 741, 5755, 1866, 1543, 680, 1, 1700, 3757, 2516, 5204, 454, 1792],
 28: [3725, 3928, 5720, 1, 3250],
 29: [5153, 2807, 2146, 3724, 5539, 1010, 4311, 5308, 2121, 5621, 1213, 1],
 30: [5521, 2459, 3046, 3142, 1],
 31: [1, 6281, 5333, 3506, 5795, 1321, 485, 1880],
 32: [436, 5291, 2178, 2574, 1719, 1, 701, 2060],
 33: [6455,
  3559,
  5867,
  6208,
  2755,
  5978,
  1160,
  3873,
  674,
  6251,
  3833,
  4965,
  5613,
  1],
 34: [1803,
  6921,
  4,
  5156,
  6583,
  1928,
  2968,
  1826,
  6750,
  3355,
  6128,
  4472,
  3711,
  1495,
  4541,
  4172,
  5516,
  6000,
  3378,
  2967,
  1,
  1043,
  4627,
  1314],
 35: [1543,
  190,
  2459,
  938,
  5808,
  6179,
  1,
  176,
  4695,
  5536,
  3861,
  5412,
  3025,
  6337,
  2755,
  1105,
  3242,
  4208,
  1843,
  481],
 36: [6297, 519, 1, 3970, 1302, 3352, 1840],
 37: [4192, 244, 5375, 4252, 1, 4816],
 38: [3050, 1, 2047, 6760, 2906],
 39: [737,
  5201,
  2673,
  282,
  2947,
  1715,
  6523,
  6408,
  2078,
  5426,
  6277,
  6411,
  879,
  281,
  6368,
  1,
  1439,
  5018,
  1957,
  5174,
  244],
 40: [1439,
  953,
  2665,
  6475,
  1482,
  3456,
  3813,
  3278,
  3046,
  1,
  674,
  3514,
  3928,
  5215,
  6135,
  2607,
  4627,
  2950,
  6977,
  485,
  5230,
  3011,
  5719,
  1070,
  6235,
  6004,
  917,
  5377,
  5813,
  6291],
 41: [1,
  5385,
  2677,
  5933,
  829,
  45,
  6313,
  5198,
  497,
  3411,
  3072,
  6728,
  4671,
  6312,
  3609,
  6735,
  6169,
  244,
  6638,
  3277,
  5978,
  5851,
  5507,
  4749,
  4420,
  3360,
  3369,
  1635,
  4623,
  2031,
  5805,
  4538,
  5409,
  3729,
  674,
  3459,
  5482,
  3284,
  6731,
  2048,
  810,
  3873],
 42: [6004,
  1727,
  419,
  6278,
  1758,
  1070,
  4007,
  741,
  4317,
  3400,
  5455,
  3373,
  79,
  4184,
  4751,
  839,
  4120,
  1,
  351,
  5898,
  3219,
  572,
  6390,
  626,
  6740,
  6134,
  726,
  6233,
  1972,
  31,
  5767,
  3523,
  832,
  744,
  2239,
  458,
  3381],
 43: [5964, 3161, 534, 3409, 192, 1],
 44: [4011,
  453,
  2045,
  5416,
  1536,
  3459,
  806,
  5074,
  200,
  4902,
  694,
  6337,
  4843,
  6506,
  2111,
  3182,
  3971,
  829,
  1232,
  1,
  4174,
  3293,
  4872,
  5677,
  6577,
  3559,
  6106,
  4907,
  1322],
 45: [5311,
  3363,
  5009,
  2382,
  4561,
  5536,
  507,
  5043,
  3585,
  1100,
  4351,
  3928,
  2642,
  3488,
  5137,
  4696,
  2322,
  4096,
  5238,
  4609,
  1636,
  3512,
  5597,
  4624,
  853,
  4774,
  5377,
  5439,
  3678,
  2571,
  5098,
  4690,
  2381,
  124,
  1,
  4742,
  2174,
  737,
  4297,
  1076,
  1070,
  2075,
  5117,
  2808,
  5099,
  3293,
  2692],
 46: [986, 1, 7049, 4946, 3387, 3523, 2764, 5182, 5055],
 47: [3900,
  3347,
  3376,
  2303,
  2122,
  4584,
  6798,
  134,
  1191,
  1755,
  1809,
  1,
  19,
  2430,
  1547,
  2403,
  1134,
  3304,
  5863,
  3890,
  444,
  990,
  1548,
  4786,
  5311,
  728,
  4203,
  2329,
  2692,
  712,
  602,
  1225,
  1361,
  3143,
  3483,
  2302,
  1345,
  2023,
  1778],
 48: [1318,
  1830,
  4688,
  2668,
  126,
  1046,
  997,
  3693,
  419,
  5900,
  2438,
  2945,
  3930,
  139,
  2671,
  1,
  6164,
  1972,
  5498,
  914,
  1649,
  4893,
  2856,
  5108,
  6264],
 49: [4025, 3548, 4691, 1318, 2108, 6902, 5981, 1, 5359, 565],
 50: [526, 1, 6149, 3757, 4668],
 51: [2, 211, 147, 279, 602],
 52: [425,
  2622,
  349,
  904,
  3632,
  2,
  26,
  1641,
  1689,
  3701,
  4746,
  2255,
  338,
  863,
  2669,
  1771,
  918,
  405,
  910,
  721,
  1767,
  1754,
  923,
  3045,
  909,
  1047,
  6779,
  1389,
  2326,
  2233,
  4727,
  749],
 53: [221, 12, 2, 9, 147, 170, 48],
 54: [251, 147, 49, 76, 196, 217, 17, 245, 2, 42],
 55: [74, 76, 92, 2, 42],
 56: [1168, 1431, 1023, 2, 24],
 57: [1921,
  6539,
  1444,
  2,
  5561,
  1232,
  2317,
  896,
  1198,
  637,
  1494,
  2346,
  2270,
  3098],
 58: [306, 452, 89, 304, 230, 245, 422, 299, 432, 154, 50, 2, 438],
 59: [2, 160, 42, 77, 80, 244, 41, 9],
 60: [259, 222, 2, 288, 80, 309, 238, 205],
 61: [2248,
  4622,
  191,
  1361,
  1832,
  2226,
  1618,
  2399,
  653,
  952,
  2177,
  1641,
  1900,
  2],
 62: [294, 157, 412, 2, 360, 9, 278, 459, 246],
 63: [1890, 217, 62, 42, 3, 198, 473, 83],
 64: [3804, 3, 2913, 853, 5181],
 65: [691, 938, 6703, 3, 3405, 1652, 6399],
 66: [5992, 5406, 5614, 3207, 1842, 3, 6101],
 67: [1043, 6776, 938, 906, 1826, 5710, 2108, 1913, 544, 312, 3, 2975],
 68: [2448, 1656, 1694, 3325, 3956, 905, 3],
 69: [4373, 5392, 3157, 2341, 707, 2717, 2459, 3, 4177, 3606, 1203],
 70: [1401, 3, 3635, 5401, 5097],
 71: [1232, 4, 5521, 2326, 2368, 848, 6100],
 72: [4402,
  3821,
  2089,
  4310,
  5928,
  6272,
  4819,
  6392,
  5637,
  4,
  2739,
  6208,
  3861,
  3844,
  4007,
  3553,
  6278,
  6511,
  1372,
  5696,
  6872,
  4539,
  5137,
  4291],
 73: [2192,
  367,
  2937,
  5224,
  2230,
  1158,
  1060,
  1986,
  4117,
  4955,
  1725,
  1585,
  4,
  4228,
  562,
  5346],
 74: [6562, 6724, 1515, 332, 2459, 5202, 6741, 4, 2330],
 75: [2326, 4724, 4, 4445, 2826, 4096],
 76: [5092, 990, 832, 1712, 2283, 1416, 4],
 77: [2430, 1323, 390, 990, 513, 1492, 4, 2695, 2692, 806],
 78: [2633, 189, 3855, 3442, 1061, 2812, 4267, 4],
 79: [3193, 4, 2089, 6582, 5826, 45],
 80: [3692,
  5911,
  4,
  3782,
  2537,
  1102,
  2244,
  5524,
  3338,
  4698,
  5555,
  2111,
  2644,
  3609,
  1955,
  5651,
  6295,
  1322,
  5425,
  5851,
  794,
  2649,
  796,
  2677,
  831,
  2396],
 81: [4627, 4, 2599, 451, 1960, 5536, 147, 4011, 4317, 1232],
 82: [904, 1958, 2524, 1261, 4, 2842, 83, 1145],
 83: [4, 2949, 1002, 4112, 1357, 1756],
 84: [1972, 6828, 2145, 591, 1846, 4, 6103, 5114],
 85: [5936, 3256, 5073, 4625, 4, 3331, 1353],
 86: [4054, 87, 5947, 4879, 5744, 4905, 4, 2108],
 87: [1656, 990, 5062, 4, 4566, 1196, 1431],
 88: [4, 5229, 938, 1111, 2516],
 89: [1585, 4, 674, 3928, 4688, 6578, 3361],
 90: [1431,
  5720,
  3629,
  5850,
  1469,
  3847,
  4375,
  4284,
  4,
  2503,
  5724,
  5610,
  5825,
  2031,
  2668],
 91: [1788, 4157, 4, 1751, 4215, 2837],
 92: [3332, 5412, 396, 4347, 5641, 4, 618, 892, 5236],
 93: [1888, 4, 3856, 5536, 6028, 3865, 4030],
 94: [4007,
  1785,
  1740,
  4043,
  2322,
  3984,
  2298,
  1837,
  45,
  4436,
  4297,
  3182,
  3671,
  1722,
  1171,
  513,
  14,
  1654,
  453,
  266,
  4,
  6087,
  53,
  5850,
  4486,
  1282,
  1322,
  3662,
  4550,
  4749,
  990,
  3262,
  4284,
  202,
  3511,
  121,
  1852,
  4991,
  5872],
 95: [2368,
  4155,
  854,
  5474,
  3169,
  3353,
  433,
  2473,
  6643,
  418,
  6918,
  1926,
  839,
  3753,
  5557,
  6892,
  6973,
  1912,
  2975,
  2414,
  2148,
  2586,
  3950,
  2221,
  281,
  1598,
  1840,
  1002,
  7,
  1979,
  1427,
  836,
  2766,
  6788,
  3373,
  752,
  829,
  2592,
  3525,
  6039,
  1096,
  3493,
  2078,
  6265,
  916,
  184,
  6263,
  3082,
  566,
  483,
  1422,
  6863,
  939,
  706,
  4,
  3413,
  1377,
  1043,
  6978,
  1758,
  5848,
  5502,
  2019,
  6953,
  1533,
  1493,
  938,
  6873,
  5069,
  6505],
 96: [5388,
  1322,
  4093,
  954,
  1790,
  1739,
  3059,
  4083,
  1529,
  6170,
  5385,
  5695,
  2300,
  4,
  2322],
 97: [4155, 4227, 4, 1987, 6278, 1002, 4821, 2474, 6280, 5421, 1171, 2485],
 98: [936, 5288, 4, 1652, 3262, 4728, 3021, 2592, 3782, 1069, 3454, 1277],
 99: [2975, 5327, 2701, 4, 691],
 100: [6322,
  3409,
  4,
  3371,
  4096,
  5311,
  3408,
  5688,
  3982,
  6224,
  2223,
  2098,
  2668],
 101: [4577,
  3356,
  4375,
  2219,
  2375,
  4438,
  2183,
  2714,
  4815,
  5811,
  4099,
  5334,
  4,
  746,
  6867,
  1498,
  2564,
  2972,
  6252,
  2755],
 102: [5900, 5524, 741, 4197, 5951, 4],
 103: [3166, 5846, 714, 4, 3225, 5343, 993, 715],
 104: [4, 4096, 4786, 1712, 4412, 3895, 938, 566, 4739, 1431],
 105: [1886, 1533, 3182, 1739, 4],
 106: [4, 6961, 971, 302, 834, 69, 4298],
 107: [1171,
  5092,
  2599,
  3380,
  5597,
  834,
  3963,
  1597,
  5544,
  2690,
  3327,
  3059,
  4,
  5085,
  5644,
  5761,
  3666,
  811],
 108: [5084, 5703, 5064, 829, 4699, 3876, 4],
 109: [1959,
  2449,
  1761,
  4,
  1164,
  6519,
  6544,
  6210,
  1323,
  4733,
  5575,
  1758,
  6212,
  1598,
  4031,
  6666,
  4233,
  3468],
 110: [4, 6483, 690, 6927, 6689],
 111: [6167, 6193, 4, 2368, 6586],
 112: [1654,
  1431,
  590,
  4007,
  1833,
  4,
  1043,
  3757,
  2711,
  2371,
  5644,
  365,
  2132,
  2891,
  1754,
  1145],
 113: [5722,
  2738,
  3967,
  1814,
  1699,
  5512,
  4,
  5914,
  6166,
  2984,
  5511,
  4392,
  944,
  2907,
  4658],
 114: [5092, 4841, 3599, 3352, 1585, 6727, 3003, 3182, 2837, 4],
 115: [5137, 4319, 5984, 1820, 2167, 3021, 1577, 2896, 5663, 3350, 4],
 116: [811, 534, 4, 139, 522],
 117: [1568, 4, 1958, 1902, 1601, 317, 5002, 2264],
 118: [2449, 1886, 1758, 1769, 1210, 1423, 4, 1153, 526],
 119: [4,
  3130,
  3342,
  3404,
  4562,
  1751,
  4375,
  4941,
  1899,
  6021,
  1754,
  2642,
  937,
  5311],
 120: [2975, 5626, 4, 4283, 5163],
 121: [24, 4367, 3928, 5455, 4, 3992],
 122: [990,
  3111,
  4552,
  3850,
  3374,
  905,
  892,
  1749,
  2746,
  2710,
  206,
  610,
  4846,
  3373,
  746,
  681,
  3522,
  1825,
  2873,
  6531,
  1780,
  1549,
  2023,
  3984,
  3981,
  2302,
  3975,
  4951,
  1886,
  4,
  4301,
  3142,
  3311,
  3619],
 123: [111, 3046, 2922, 3076, 2474, 4, 1788],
 124: [3207, 3876, 990, 6973, 566, 2194, 4],
 125: [3928, 4719, 4, 4440, 4199, 1502, 937],
 126: [1585, 3973, 4, 2658, 2359],
 127: [5825, 2005, 4, 1431, 3675, 5137, 2219],
 128: [3241,
  2554,
  3526,
  774,
  1860,
  419,
  2717,
  1043,
  374,
  1739,
  5,
  1201,
  6139,
  1932,
  3024,
  2677],
 129: [4847, 1799, 5, 5526, 2961, 1241, 3901, 3617, 2121, 3029],
 130: [1215,
  367,
  2718,
  1749,
  2128,
  1120,
  466,
  562,
  4437,
  711,
  2244,
  3561,
  472,
  3514,
  434,
  1460,
  3725,
  557,
  641,
  405,
  2251,
  1691,
  750,
  4128,
  3564,
  606,
  948,
  3559,
  3331,
  1332,
  2070,
  662,
  3352,
  1083,
  317,
  2416,
  3443,
  3430,
  3668,
  3262,
  3403,
  1888,
  3154,
  3555,
  4353,
  1808,
  1773,
  1840,
  980,
  322,
  3860,
  2322,
  684,
  1287,
  124,
  163,
  1527,
  1636,
  5,
  289,
  528,
  563,
  2568,
  76,
  1853,
  3562,
  10,
  2571,
  2139,
  1668,
  873,
  2447,
  864,
  2167,
  4807,
  2777,
  168,
  1210,
  3876,
  626,
  1798,
  963,
  917,
  3599,
  4350,
  11,
  2881,
  388,
  1140],
 131: [4139, 1727, 5, 1671, 946, 590],
 132: [4900,
  744,
  2132,
  1303,
  2668,
  485,
  1754,
  5761,
  5,
  1758,
  6330,
  5734,
  673,
  6027,
  3876],
 133: [6331,
  425,
  5411,
  3956,
  3034,
  4402,
  2831,
  5,
  4197,
  3361,
  5590,
  4454,
  4282,
  5412,
  2150,
  3960,
  6961,
  3377,
  6278],
 134: [1568, 2235, 6, 1215, 1498, 2233, 989],
 135: [21, 6, 42, 9, 152],
 136: [79, 61, 6, 181, 128, 219, 108, 65, 63],
 137: [101,
  6,
  170,
  76,
  160,
  77,
  12,
  56,
  58,
  42,
  103,
  34,
  64,
  158,
  40,
  126,
  106],
 138: [6, 126, 9, 76, 22, 70],
 139: [333, 2639, 3364, 5377, 7],
 140: [7, 2377, 6346, 3194, 5643, 482],
 141: [482, 933, 4338, 7, 1926, 387, 1184, 1758, 1091],
 142: [6724,
  1165,
  1093,
  873,
  6237,
  2329,
  1392,
  3182,
  245,
  1649,
  7,
  333,
  499,
  482,
  828,
  4607,
  1357,
  3172],
 143: [7, 24, 1344, 2531, 1431],
 144: [222, 8, 147, 218, 128],
 145: [8, 187, 179, 82, 170, 9],
 146: [147, 79, 303, 166, 8, 399, 553, 339, 403],
 147: [376, 116, 247, 9, 553, 8, 102],
 148: [1791, 8, 1621, 3722, 293, 5310, 1055, 141, 1075, 771],
 149: [102, 459, 8, 340, 376, 599, 85, 221, 247, 299],
 150: [8, 21, 163, 4038, 4975, 96, 524, 3059],
 151: [168,
  246,
  74,
  303,
  216,
  119,
  413,
  41,
  58,
  328,
  167,
  108,
  8,
  217,
  75,
  159,
  62,
  176],
 152: [408, 289, 428, 419, 9],
 153: [1422, 1479, 9, 2026, 5635, 836],
 154: [244,
  428,
  96,
  251,
  187,
  212,
  12,
  350,
  399,
  149,
  1059,
  238,
  174,
  38,
  36,
  464,
  201,
  128,
  42,
  200,
  43,
  9],
 155: [225, 552, 1031, 491, 9, 968],
 156: [812, 627, 22, 9, 428],
 157: [9, 238, 97, 46, 55, 457, 529, 187, 303, 323],
 158: [601, 428, 9, 1069, 1002, 187],
 159: [117, 415, 9, 301, 102],
 160: [163, 55, 101, 9, 212, 70],
 161: [152, 63, 187, 9, 181, 278],
 162: [480, 201, 435, 9, 187, 203],
 163: [419, 9, 185, 79, 203],
 164: [428, 416, 9, 289, 306, 311, 242],
 165: [294, 459, 187, 9, 42, 245],
 166: [706, 289, 669, 9, 63],
 167: [3341, 305, 336, 43, 222, 181, 56, 9, 398, 250],
 168: [185, 203, 9, 249, 308],
 169: [3333, 2264, 3386, 425, 669, 3853, 9, 4204],
 170: [187, 221, 280, 9, 185],
 171: [48, 53, 9, 406, 500, 468, 185, 6833, 52, 679],
 172: [102, 235, 43, 9, 311, 108, 42, 187, 277, 89],
 173: [171, 299, 218, 9, 102, 187, 29],
 174: [176, 9, 274, 2205, 336],
 175: [9, 249, 21, 102, 1226, 149],
 176: [459, 457, 587, 552, 428, 9],
 177: [926, 1785, 9, 31, 2072, 1105, 1462, 245],
 178: [9, 245, 459, 1226, 174],
 179: [187, 126, 43, 379, 9],
 180: [206, 246, 9, 215, 250, 340],
 181: [9, 378, 437, 480, 346, 459, 128],
 182: [225, 275, 339, 76, 172, 9, 39, 56, 22, 187],
 183: [294, 346, 9, 480, 187],
 184: [9, 34, 185, 42, 225],
 185: [379, 9, 272, 110, 217, 187],
 186: [413, 308, 428, 9, 379],
 187: [117, 76, 9, 141, 108],
 188: [2183, 9, 1080, 37, 5480],
 189: [119, 10, 9, 233, 439, 35],
 190: [500, 553, 461, 9, 42],
 191: [53, 9, 155, 280, 295],
 192: [2684,
  602,
  562,
  1643,
  2114,
  1285,
  2476,
  1525,
  668,
  643,
  9,
  2248,
  954,
  878,
  1483],
 193: [4011, 5305, 187, 223, 9, 23],
 194: [77, 9, 126, 172, 147],
 195: [9, 185, 56, 85, 76],
 196: [210, 31, 264, 213, 9, 341, 182],
 197: [309, 9, 428, 366, 175, 141, 106],
 198: [437, 459, 9, 168, 250, 187, 117],
 199: [339, 9, 408, 535, 427, 341, 350],
 200: [428, 500, 9, 459, 249],
 201: [245, 9, 77, 258, 79, 1493],
 202: [154, 333, 399, 9, 222, 274],
 203: [275, 9, 437, 459, 755],
 204: [471, 442, 9, 175, 36, 96, 323, 309, 55, 97, 202, 499, 300],
 205: [350, 126, 128, 53, 9, 1515, 197, 79],
 206: [684, 341, 481, 9, 303],
 207: [1023, 9, 480, 79, 2016],
 208: [187, 239, 238, 428, 9, 110],
 209: [366, 412, 305, 9, 280, 239, 274],
 210: [278, 9, 326, 360, 336, 289],
 211: [428, 346, 505, 553, 350, 9],
 212: [9, 1226, 294, 50, 42, 76, 206],
 213: [251,
  141,
  9,
  311,
  2016,
  235,
  128,
  167,
  187,
  214,
  429,
  341,
  303,
  476,
  106,
  248,
  275],
 214: [114, 459, 236, 1226, 104, 413, 488, 9, 225],
 215: [157, 234, 150, 1793, 9],
 216: [459, 9, 75, 187, 154, 419, 43],
 217: [223, 235, 1226, 9, 311, 187, 294, 175, 460],
 218: [9, 249, 265, 1226, 22, 201],
 219: [6935,
  4781,
  4059,
  6352,
  4513,
  7020,
  4904,
  6993,
  457,
  6124,
  42,
  7000,
  48,
  6906,
  3930,
  6564,
  5538,
  9,
  4352,
  6859,
  6265,
  61,
  6603,
  6281,
  7028,
  4872,
  3848,
  5192,
  458,
  95,
  7005,
  4788,
  6063,
  6294,
  6522,
  6226,
  6537,
  6409,
  7038,
  6947,
  3686,
  57,
  2507,
  6918,
  27,
  6863,
  6964,
  5488,
  6772,
  6814,
  6787,
  6958,
  160,
  6812,
  4351,
  6661,
  5409,
  6783,
  6967,
  6069,
  4350,
  119,
  2241,
  3562,
  6976,
  77,
  1809,
  6995,
  6907,
  6420,
  6274,
  6349,
  5872],
 220: [399, 459, 9, 288, 206, 336],
 221: [122, 203, 65, 82, 217, 9],
 222: [102, 235, 308, 79, 341, 289, 301, 119, 153, 181, 9],
 223: [56, 428, 304, 376, 187, 9],
 224: [274, 22, 336, 416, 599, 9, 96],
 225: [1226, 218, 289, 187, 459, 9, 412, 74, 76, 398],
 226: [9, 10, 163, 247, 77, 303, 79],
 227: [82, 280, 326, 293, 21, 116, 9, 287, 125],
 228: [1226, 9, 187, 303, 438],
 229: [459, 243, 175, 79, 350, 9],
 230: [399, 203, 67, 240, 22, 238, 480, 459, 9],
 231: [227, 187, 324, 9, 336, 245, 278],
 232: [75, 278, 9, 1226, 324, 245, 259],
 233: [117, 187, 74, 128, 9],
 234: [298, 42, 247, 79, 9, 276, 216, 294, 119, 21, 102],
 235: [9, 340, 38, 274, 459],
 236: [206, 63, 23, 9, 102, 79, 220, 46],
 237: [10, 9, 185, 56, 79, 42],
 238: [207, 428, 336, 117, 9, 422],
 239: [9, 76, 54, 147, 33, 185, 98],
 240: [412, 210, 9, 154, 214, 379, 269, 231],
 241: [83, 336, 141, 308, 50, 427, 408, 9],
 242: [241, 222, 85, 1226, 102, 9, 163, 79, 76],
 243: [67, 278, 10, 116, 1152, 9, 207, 325, 1226],
 244: [495, 126, 187, 416, 9],
 245: [175, 198, 303, 550, 9],
 246: [9, 119, 22, 413, 437],
 247: [269, 185, 341, 9, 428, 279, 174, 419],
 248: [9, 42, 207, 76, 246, 211, 299, 92],
 249: [341, 119, 9, 419, 42, 417, 108, 611, 229, 76],
 250: [306, 42, 9, 336, 300],
 251: [63, 399, 428, 366, 9],
 252: [9, 3443, 662, 76, 744],
 253: [428, 1042, 459, 416, 9],
 254: [9, 459, 294, 429, 252],
 255: [9,
  3724,
  6639,
  646,
  2722,
  704,
  2303,
  5556,
  1863,
  4425,
  1493,
  1830,
  513,
  1300,
  4893,
  388,
  2473],
 256: [553, 657, 459, 201, 927, 33, 311, 9],
 257: [203, 239, 85, 9, 182, 21],
 258: [565, 342, 1031, 176, 43, 76, 9],
 259: [22, 9, 360, 428, 554],
 260: [459, 9, 426, 79, 245],
 261: [1617, 303, 553, 1091, 9, 752, 185, 1363, 904, 773, 464, 84, 307],
 262: [1997, 9, 1830, 923, 48, 108, 550],
 263: [9,
  500,
  163,
  210,
  221,
  303,
  191,
  419,
  108,
  324,
  181,
  250,
  212,
  74,
  245,
  452,
  114,
  76,
  433,
  218,
  294,
  264,
  251,
  216,
  81,
  77,
  336,
  341,
  377],
 264: [9, 61, 76, 80, 42],
 265: [427, 9, 21, 461, 288],
 266: [1160, 187, 102, 3484, 2146, 9, 2515, 41, 1789, 3283],
 267: [76, 9, 42, 126, 83],
 268: [245, 9, 141, 428, 311],
 269: [285, 249, 96, 9, 50, 272, 289, 227, 298, 75, 303],
 270: [408, 79, 166, 9, 459],
 271: [303, 233, 117, 247, 459, 223, 9, 245, 75, 55, 427],
 272: [74, 42, 79, 9, 55],
 273: [76, 75, 1041, 102, 185, 171, 433, 9, 250, 376],
 274: [1152, 711, 408, 192, 5930, 9, 5740, 249],
 275: [9, 480, 187, 238, 419, 333],
 276: [207, 46, 9, 245, 223],
 277: [203, 306, 9, 223, 437, 553, 274, 241, 55],
 278: [613, 187, 65, 408, 9],
 279: [9, 432, 250, 350, 269],
 280: [206, 399, 419, 225, 9],
 281: [6998,
  42,
  7005,
  6116,
  6788,
  6811,
  419,
  2776,
  308,
  43,
  7042,
  7011,
  403,
  249,
  360,
  9,
  6787,
  2016,
  6732,
  604],
 282: [1830, 303, 191, 187, 89, 9, 613, 203, 269, 459],
 283: [185, 21, 191, 10, 187, 202, 9, 210],
 284: [128, 459, 657, 9, 245, 428],
 285: [236, 9, 214, 34, 126],
 286: [9, 163, 555, 1980, 175, 203, 671, 219, 85],
 287: [9, 1046, 1790, 1033, 334, 938, 303, 1953],
 288: [1226, 341, 147, 413, 80, 9],
 289: [247, 58, 187, 9, 213, 240, 274, 10, 302, 244, 76, 181, 238, 102, 42],
 290: [9, 1046, 294, 275, 408],
 291: [64, 128, 39, 93, 106, 9, 126],
 292: [244,
  246,
  366,

In [9]:
new_label = []
u_ids_sorted = sorted(u_i_dict.keys())

for u in u_ids_sorted:
    items = u_i_dict[u]
    n_items = len(items)
    if n_items < 10:
        tmp_ls = [0] * (n_items - 2) + [1] + [2]
    else:
        val_test_len = int(n_items * 0.2)
        train_len = n_items - val_test_len
        val_len = val_test_len // 2
        test_len = val_test_len - val_len
        tmp_ls = [0] * train_len + [1] * val_len + [2] * test_len
    new_label.extend(tmp_ls)

new_label[:100]

[0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0]

In [10]:
df['x_label'] = new_label
df[:20]

        userID  itemID  rating   timestamp  x_label
37004        0    3870     4.0  1357689600        0
101836       0    1879     5.0  1373932800        0
117802       0    1922     5.0  1363996800        0
155842       0    1587     5.0  1373932800        1
20530        0       0     5.0  1373932800        2
137704       1    1434     5.0  1372377600        0
38052        1       0     5.0  1372464000        0
40236        1    5176     5.0  1372464000        0
154030       1    1177     5.0  1372464000        0
101481       1    5403     5.0  1367452800        1
15671        1    2828     5.0  1372464000        2
4613         2    2846     2.0  1395187200        0
38495        2       0     5.0  1395187200        0
7832         2    6578     3.0  1387497600        0
142678       2    4011     5.0  1387497600        1
121376       2    6735     5.0  1395187200        2
61509        3    1886     5.0  1376697600        0
109518       3     638     4.0  1376697600        0
30241        3    2755     2.0  1376697600        0
93692        3       0     5.0  1376697600        0

In [11]:
rslt_file[:-6]

'baby-indexed'

In [12]:
new_labeled_file = rslt_file[:-6] + '-v4.inter'
df.to_csv(os.path.join('./', new_labeled_file), sep='\t', index=False)
print('done!!!')

done!!!

## Reload

In [13]:
indexed_df = pd.read_csv(new_labeled_file, sep='\t')
print(f'shape: {indexed_df.shape}')
indexed_df[:20]

shape: (160792, 5)

    userID  itemID  rating   timestamp  x_label
0        0    3870     4.0  1357689600        0
1        0    1879     5.0  1373932800        0
2        0    1922     5.0  1363996800        0
3        0    1587     5.0  1373932800        1
4        0       0     5.0  1373932800        2
5        1    1434     5.0  1372377600        0
6        1       0     5.0  1372464000        0
7        1    5176     5.0  1372464000        0
8        1    1177     5.0  1372464000        0
9        1    5403     5.0  1367452800        1
10       1    2828     5.0  1372464000        2
11       2    2846     2.0  1395187200        0
12       2       0     5.0  1395187200        0
13       2    6578     3.0  1387497600        0
14       2    4011     5.0  1387497600        1
15       2    6735     5.0  1395187200        2
16       3    1886     5.0  1376697600        0
17       3     638     4.0  1376697600        0
18       3    2755     2.0  1376697600        0
19       3       0     5.0  1376697600        0

In [14]:
u_id_str, i_id_str = 'userID', 'itemID'
u_uni = indexed_df[u_id_str].unique()
c_uni = indexed_df[i_id_str].unique()

print(f'# of unique learners: {len(u_uni)}')
print(f'# of unique courses: {len(c_uni)}')

print('min/max of unique learners: {0}/{1}'.format(min(u_uni), max(u_uni)))
print('min/max of unique courses: {0}/{1}'.format(min(c_uni), max(c_uni)))

# of unique learners: 19445
# of unique courses: 7050
min/max of unique learners: 0/19444
min/max of unique courses: 0/7049